// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by go-simpler.org/assert/cmd/copier. DO NOT EDIT.

// Package dotimport provides type aliases for the parent [assert] package.
// It is intended to be dot-imported so that [E] and [F] can be used as local types.
package dotimport

import "go-simpler.org/env/internal/assert"

type (
	E = assert.E
	F = assert.F
)
