linters:
  disable-all: true
  enable:
    # enabled by default:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # disabled by default:
    # - gocritic TODO(junk1tm): enable when github.com/go-critic/go-critic/issues/1193 is closed
    - gofumpt

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
